- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - basic-check-spec
    image: harbor.nonprod.caas.energy.sug.pri/transpara-dev/scorecard-test:v1.34.1
    labels:
      suite: basic
      test: basic-check-spec-test
