---
# Source: tstore-interface/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tstore-interface-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tstore-interface
  template:
    metadata:
      labels:
        app: tstore-interface
    spec:
      containers:
      - name: tstore-interface
        image: "transpara/tstore-interface:kube-test"
        imagePullPolicy: Always
      envFrom:
      - configMapRef:
          name: tstore-interface-config
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
      imagePullSecrets:
      - name: transpara-docker-secret
      
