apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tcoreFlower.deployment.name }}
spec:
  replicas: {{ .Values.tcoreFlower.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tcoreFlower.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tcoreFlower.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.tcoreFlower.deployment.name }}
        image: "{{ .Values.tcoreFlower.image.repository }}:{{ .Values.tcoreFlower.image.tag }}"
        command: ["/app/run-flower.sh"]
        ports:
        - containerPort: {{ .Values.tcoreFlower.containerPort }}
        env:
        - name: TCORE_NAME
          value: {{ .Values.tcoreFlower.config.TCORE_NAME }}
        - name: CELERY_BROKER_URL
          value: "redis://{{ .Values.tcoreFlower.config.REDIS_HOST }}:{{ .Values.tcoreFlower.config.REDIS_PORT }}/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://{{ .Values.tcoreFlower.config.REDIS_HOST }}:{{ .Values.tcoreFlower.config.REDIS_PORT }}/1"
        # Additional environment variables can be added as needed
