# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/charts.transpara.com_tsystems.yaml
- bases/charts.transpara.com_tstoreinterfaces.yaml
- bases/charts.transpara.com_tauths.yaml
- bases/charts.transpara.com_extractorodbcs.yaml
- bases/charts.transpara.com_collectortelegrafs.yaml
- bases/charts.transpara.com_extractoropcuas.yaml
#+kubebuilder:scaffold:crdkustomizeresource
