apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/transpara: "true"
        io.kompose.service: jaeger
    spec:
      containers:
        - env:
            - name: GRPC_STORAGE_SERVER
              value: ':'
            - name: SPAN_STORAGE_TYPE
              value: grpc-plugin
          image: jaegertracing/jaeger-query:1.30
          name: tdebug-jaeger
          ports:
            - containerPort: 16686
              hostIP: 0.0.0.0
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
