apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: pg-admin
  name: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pg-admin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/transpara: "true"
        io.kompose.service: pg-admin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
          image: dpage/pgadmin4
          name: tdebug-pgadmin
          ports:
            - containerPort: 80
              hostIP: 0.0.0.0
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
