version: "3.9"
   
services:

  tcalc-main:
    labels:
      - "Module=Main"
      - "Version=${TCALC_TAG}"
      - "ID=${TCALC_ID}"
    image: "transpara/tcalc:${TCALC_TAG}"  
    command: /app/entry-main.sh
    container_name: ${TCALC_NAME}_main
    hostname: ${TCALC_NAME}_main
    ports:
      - "${TCALC_FLOWER_PORT}:5555"    
      - "${TCALC_API_PORT}:10003"    
    restart: unless-stopped     
    volumes:
      - tcalc_modules:/app/app/extensions  
    environment:
      - REDIS_HOST=${TSYSTEM_NAME}_cache
      - REDIS_PORT=${TREDIS_PORT}         
      - REDIS_CELERY_BROKER_DB=5
      - REDIS_CELERY_RESULT_DB=6
      - REDIS_SNAPSHOT_DB=7    
      - TSYSTEM_API_URL=http://${TSYSTEM_NAME}_api:80/api/v1
      - TSTORE_API_URL=http://${TSTORE_NAME}_api:80/api/v1
      - CONFIG_DB_URL=postgresql://${TSTORE_UNAME}:${TSTORE_PASSWORD}@${TSTORE_NAME}_db:5432/${TSTORE_DBNAME}
      - CACHE_CALCULATIONS_SEC=30 
      - VERSION=${TCALC_TAG}      
   

  tcalc-worker:
    labels:
      - "Module=Worker"
      - "Version=${TCALC_TAG}"
      - "ID=${TCALC_ID}"
    image: "transpara/tcalc:${TCALC_TAG}"  
    command: /app/run-celeryworker.sh
    container_name: ${TCALC_NAME}_worker
    hostname: ${TCALC_NAME}_worker
    restart: unless-stopped     
    volumes:
      - tcalc_modules:/app/app/extensions      
    environment:
      - REDIS_HOST=${TSYSTEM_NAME}_cache
      - REDIS_PORT=${TREDIS_PORT}          
      - REDIS_CELERY_BROKER_DB=5
      - REDIS_CELERY_RESULT_DB=6
      - REDIS_SNAPSHOT_DB=7
      - TSTORE_API_URL=http://${TSTORE_NAME}_api:80/api/v1
      - TSYSTEM_API_URL=http://${TSYSTEM_NAME}_api:80/api/v1
      - CONFIG_DB_URL=postgresql://${TSTORE_UNAME}:${TSTORE_PASSWORD}@${TSTORE_NAME}_db:5432/${TSTORE_DBNAME}
      - CACHE_CALCULATIONS_SEC=30     

  code-server:
    labels:
      - "Version=${TCALC_TAG}"
      - "ID=${TCALC_ID}"
    image: "transpara/tcode:${TCALC_TAG}"
    container_name: ${TCALC_NAME}_vscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DEFAULT_WORKSPACE=/extensions
    volumes:
      - tcalc_modules:/extensions
    ports:
      - ${VSCODE_PORT}:8443
    restart: unless-stopped



networks:
   default:
      name: transpara
      external: true


volumes:
   tcalc_modules:
      name: tcalc_modules_${TCALC_ID}
