apiVersion: charts.transpara.com/v1
kind: TStoreInterface
metadata:
  name: tstore-interface
spec:
  global:
    imagePullSecret: transpara-docker-secret
    imagePullPolicy: Always
    
  tStoreInterface:
    name: tstore-interface
    replicas: 1
    image:
      repository: transpara/tstore-interface
      tag: 0.157.1
    config:
      # Example: http://tsystem-api-service:80/api/v1
      TSYSTEM_URL: <<TSYSTEM_URL>>
      # Example: postgresql://postgres:a0ba-396f-4c57-9b4@my-db-primary:5432/postgres
      TSTORE_DB_URL: <<TSTORE_CONNECTION_STRING>>
      EXPOSE_METRICS: "true"
      TSTORE_ID: <<TSTORE_ID>>
      TCACHE_HOST: tsystem-cache
      TCACHE_PORT: "6379"
      TCACHE_DB: "7"
      TCACHE_CONSIDER_STALE_SEC: "300"
      LOG_LEVEL: INFO
      BASE_PATH: "/tstore-interface"
    ports:
      - containerPort: 80
    service:
      type: NodePort
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30083
