apiVersion: charts.transpara.com/v1
kind: ExtractorOdbc
metadata:
  name: todbc
spec:
  imagePullSecret: transpara-docker-secret
  imagePullPolicy: Always
  name: todbc
  serviceName: tsystem-api
  replicas: 1
  image:
    repository: transpara/extractor-odbc
    tag: 0.179.0
  config:
    ID: 7eef
    EXTRACTOR_PREFIX: odbc
    TSTORE_API_URL: http://tstore-interface:80/tstore/
    TSTORE_FLUSH_INTERVAL_SECONDS: 10
    TSTORE_FLUSH_SIZE: 100
    OUTPUT_BATCH_SIZE: 20
    CYCLE_SECONDS: 20
    LOOKBACK_SECONDS: 1800
    MAX_RANGE_PER_REQUEST_SECONDS: 86400
    BACKFILL_START_TIME: 2023-08-10
    BACKFILL: true
    CONNECTION_STRING: Driver={PostgreSQL Unicode};Server=<server_ip_address>;Port=<server_port>;Database=postgres;Uid=postgres;Pwd=<password>;
    TSYSTEM_HOST: tsystem-api
    QUERY: Select metric, value, ts, comma_delimitted_labels from your_table
    SOURCE_TZ: UTC
    LOG_ENQUEING: true
    LOG_QUERY: true
