apiVersion: charts.transpara.com/v1
kind: ExtractorOdbc
metadata:
  name: <<NAME>>
spec:
  tOdbc:
    imagePullSecret: transpara-docker-secret
    imagePullPolicy: Always
    name: <<NAME>>
    replicas: 1
    image:
      repository: transpara/extractor-odbc
      tag: 0.179.0
    config:
      ID: <<ID>> 
      EXTRACTOR_PREFIX: <<EXTRACTOR_PREFIX>>
      TSTORE_API_URL: <<TSTORE_API_URL>>
      TSTORE_FLUSH_INTERVAL_SECONDS: <<TSTORE_FLUSH_INTERVAL_SECONDS>>
      TSTORE_FLUSH_SIZE: <<TSTORE_FLUSH_SIZE>>
      OUTPUT_BATCH_SIZE: <<OUTPUT_BATCH_SIZE>>
      CYCLE_SECONDS: <<CYCLE_SECONDS>>
      LOOKBACK_SECONDS: <<LOOKBACK_SECONDS>>
      MAX_RANGE_PER_REQUEST_SECONDS: <<MAX_RANGE_PER_REQUEST_SECONDS>>
      BACKFILL_START_TIME: <<BACKFILL_START_TIME>>
      BACKFILL: <<BACKFILL>>
      # Driver={PostgreSQL Unicode};Server=<server_ip_address>;Port=<server_port>;Database=postgres;Uid=postgres;Pwd=<password>;
      CONNECTION_STRING: <<CONNECTION_STRING>>
      TSYSTEM_HOST: <<TSYSTEM_HOST>>
      # Select metric, value, ts, comma_delimited_labels from your_table
      QUERY: <<QUERY>> 
      SOURCE_TZ: <<SOURCE_TZ>>
      LOG_ENQUEING: true
      LOG_QUERY: true

