apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.tStoreInterface.name }}-route
spec:
  parentRefs:
  - name: tsystem-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/tstore/ui"
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "/"
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
          - name: X-Forwarded-Prefix
            value: "/tstore/ui"
    backendRefs:
    - name: {{ .Values.tStoreUi.name }}
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: "{{ .Values.tStoreInterface.config.BASE_PATH }}"
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "/"
    backendRefs:
    - name: {{ .Values.tStoreInterface.name }}
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: "/tstore"
    filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: "http"
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "/tstore/ui"
