apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.tStoreInterface.name }}-route
  namespace: default
spec:
  parentRefs:
  - name: tgateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "{{ .Values.tStoreUi.config.BASE_PATH }}"
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "/"
    - type: AddRequestHeader
      addRequestHeader:
        name: X-Forwarded-Prefix
        value: "{{ .Values.tStoreUi.config.BASE_PATH }}"
    backendRefs:
    - name: {{ .Values.tStoreUi.name }}
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: "/tstore"
    filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: "http"
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "{{ .Values.tStoreUi.config.BASE_PATH }}"
    backendRefs:
    - name: {{ .Values.tStoreUi.name }}
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: "{{ .Values.tStoreInterface.config.BASE_PATH }}"
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "/"
    backendRefs:
    - name: {{ .Values.tStoreInterface.name }}
      port: 80
