apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tStoreUi.name }}
spec:
  replicas: {{ .Values.tStoreUi.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tStoreUi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tStoreUi.name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 6006
        fsGroup: 6006
      containers:
      - name: {{ .Values.tStoreUi.name }}
        image: "{{ .Values.tStoreUi.image.repository }}:{{ .Values.tStoreUi.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
{{ toYaml .Values.tStoreInterface.ports | indent 10 }}
        env:
        - name: TSTORE_INTERFACE_URL
          value: "http://{{ .Values.tStoreInterface.name }}:{{ (index .Values.tStoreInterface.ports 0).containerPort }}{{ .Values.tStoreInterface.config.BASE_PATH }}"
        - name: VERSION
          value: "{{ .Values.tStoreUi.image.tag }}"
        - name: LOG_LEVEL
          value: "{{ .Values.tStoreUi.config.LOG_LEVEL | default .Values.global.logLevel }}"
        - name: BASE_PATH
          value: "{{ .Values.tStoreUi.config.BASE_PATH }}"
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}