apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tsystem-api
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`{{ .Values.tSystemUi.config.BASE_PATH }}`)
      kind: Rule
      services:
        - name: tsystem-ui
          port: 3000
    - match: PathPrefix(`/tsystem`) # This will match any subpath not exclusively caught by the above
      kind: Rule
      middlewares:
        - name: redirect-to-ui
      services:
        - name: tsystem-ui
          port: 3000
    - match: PathPrefix(`{{ .Values.tSystemApi.config.BASE_PATH }}`)
      kind: Rule
      services:
        - name: tsystem-api
          port: 80
      middlewares:
        - name: strip-prefix
