apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.tSystemCache.name }}
spec:
  serviceName: {{ .Values.tSystemCache.name }}
  replicas: {{ .Values.tSystemCache.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tSystemCache.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tSystemCache.name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 6006
      containers:
      - name: {{ .Values.tSystemCache.name }}
        image: "{{ .Values.tSystemCache.image.repository }}:{{ .Values.tSystemCache.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.tSystemCache.ports.containerPort }}
        volumeMounts: 
        - name: {{ .Values.tSystemCache.volumeMount.name }}
          mountPath: {{ .Values.tSystemCache.volumeMount.mountPath }}
      imagePullSecrets: 
        - name: {{ .Values.global.imagePullSecret }}
      volumes:
        - name: {{ .Values.tSystemCache.volumeMount.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.tSystemCachePvc.name }}
