global:
  imagePullSecret: transpara-docker-secret

tcoreApi:
  service:
    name: tcore-api
    type: NodePort
    port: 80
    nodePort: 30010
  deployment:
    name: tcore-api
    replicas: 1
  containerPort: 80
  image:
    repository: transpara/tcore-api
    tag: develop
  config:
    TCORE_NAME: version_six
    TGRAPH_HOST: memgraph-db
    TGRAPH_PORT: 7687
    REDIS_HOST: tsystem-cache
    REDIS_PORT: 6379
    TAUTH_HOST: tsystem-tauth
    TAUTH_PORT: 8080
    TCORE_ID: 049f6ed7-e754-4315-bdc6-bf5ed6e4d437
    OTEL_EXPORTER_HOST: tstore_tscale

tcoreBeat:
  deployment:
    name: tcore-beat
    replicas: 1
  image:
    repository: transpara/tcore-api
    tag: develop
  config:
    TCORE_NAME: version_six
    TGRAPH_HOST: tcore-beat-tcore-db
    TGRAPH_PORT: 7687
    REDIS_HOST: tsystem-cache
    REDIS_PORT: 6379
    TAUTH_HOST: tsystem-tauth
    TAUTH_PORT: 8080
    TCORE_ID: 049f6ed7-e754-4315-bdc6-bf5ed6e4d437

tcoreWorker:
  deployment:
    name: tcore-worker
    replicas: 1
  image:
    repository: transpara/tcore-api
    tag: develop
  config:
    TCORE_NAME: version_six
    TGRAPH_HOST: tcore-worker-tcore-db
    TGRAPH_PORT: 7687
    REDIS_HOST: tsystem_tcache
    REDIS_PORT: 6379
    TAUTH_HOST: tsystem_tauth
    TAUTH_PORT: 8080
    TCORE_ID: 049f6ed7-e754-4315-bdc6-bf5ed6e4d437
    OTEL_EXPORTER_HOST: tstore_tscale

tcoreFlower:
  deployment:
    name: tcore-flower
    replicas: 1
  containerPort: 5555
  image:
    repository: transpara/tcore-api
    tag: develop
  config:
    TCORE_NAME: version_six
    REDIS_HOST: tsystem-cache
    REDIS_PORT: 6379

tcoreUi:
  service:
    name: tcore-ui
    type: ClusterIP
    port: 3000
    nodePort: null
  deployment:
    name: tcore-ui
    replicas: 1
  containerPort: 3000
  image:
    repository: transpara/tcore-ui
    tag: develop
  config:
    TCORE_UI_PATH: VisualKPI
    TCORE_HOST: 172.21.53.75
    TCORE_PORT: 30010

memgraphDb:
  service:
    name: memgraph-db
    type: ClusterIP
    port: 7687
    nodePort: null
  name: memgraph-db
  replicas: 1
  ports:
    containerPort: 7687
  image:
    repository: memgraph/memgraph-platform
    tag: 2.3.1
  volumeMount:
    name: memgraph-volume
    mountPath: /var/lib/memgraph
  imagePullPolicy: IfNotPresent

memgraphDbPvc:
  name: tcore-data-pvc

