replicaCount: 1
image:
  repo: "transpara/collector-telegraf"
  tag: "0.178.0"
  pullPolicy: IfNotPresent
podAnnotations: {}
podLabels: {}
imagePullSecrets: 
  - name: transpara-docker-secret
args: []
env:
  - name: HOSTNAME
    value: "telegraf-polling-service"
resources: {}
nodeSelector: {}
affinity: {}
tolerations: []
updateStrategy: {}
service:
  enabled: true
  type: ClusterIP
  annotations: {}
rbac:
  create: true
  clusterWide: true
  rules:
    - apiGroups:
        - ""
      resources:
        - nodes
        - nodes/proxy
        - nodes/metrics
        - services
        - endpoints
        - pods
        - ingresses
        - configmaps
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - "extensions"
      resources:
        - ingresses/status
        - ingresses
      verbs:
        - get
        - list
        - watch
    - nonResourceURLs:
        - "/metrics"
      verbs:
        - get
serviceAccount:
  create: true
  name: ""
  annotations: {}
config:
  agent:
    interval: "10s"
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
    precision: ""
    debug: false
    quiet: false
    logfile: ""
    hostname: "K8S_TEST"
    omit_hostname: false
  processors:
    - enum:
        mapping:
          field: "status"
          dest: "status_code"
          value_mappings:
            healthy: 1
            problem: 2
            critical: 3
  outputs:
    - execd:
        alias: "telegraf"
        command: [ "python", "/app/output_tstore.py" ]
        data_format: "json"
        restart_delay: "60s"
        environment: 
          - "TSTORE_API_URL=http://tstore-interface/tstore/"
          - "TSTORE_FLUSH_INTERVAL_SECONDS=10"
          - "TSTORE_FLUSH_SIZE=500"
          - "OUTPUT_BATCH_SIZE=1000"
          - "TSYSTEM_SETTINGS_TIMEOUT=10"
          - "TSYSTEM_HOST=tsystem-api"
          - "SOURCE_TZ=UTC"
          - "LOG_ENQUEUING=true"
  inputs:
    - cpu:
        percpu: true
        totalcpu: true
        collect_cpu_time: false
        report_active: false
        core_tags: false
        alias: "telegraf"
metrics:
  health:
    enabled: false
    service_address: "http://:8888"
    threshold: 5000.0
  internal:
    enabled: true
    collect_memstats: false
pdb:
  create: false
  minAvailable: 1