global:
  imagePullSecret: transpara-docker-secret
  imagePullPolicy: Always

tOpcua:
  name: opcua
  replicas: 1
  image:
    repository: transpara/tstore_opcua_collector
    tag: 1.0.0
  config:
    OPCUA_ENDPOINT_URL: example_endpoint_url