version: "3.9"
   
services:

  tstore_interface:
    labels:
      - "Version=${TSTORE_INTERFACE_TAG}"
      - "ID=${TSTORE_ID}"
    image: "transpara/tstore-interface:${TSTORE_INTERFACE_TAG}"
    environment:
      - TSYSTEM_URL=${TSYSTEM_URL}    
      - TSTORE_DB_READ_URL=${TSTORE_DB_READ_URL}
      - TSTORE_DB_WRITE_URL=${TSTORE_DB_READ_URL}
      - EXPOSE_METRICS=${EXPOSE_METRICS}
      - TSTORE_ID=${TSTORE_ID}
      - TCACHE_HOST=${TCACHE_HOST}
      - TCACHE_PORT=${TCACHE_PORT}  
      - TCACHE_DB=${TCACHE_DB}  
      - TCACHE_CONSIDER_STALE_SEC=${TCACHE_CONSIDER_STALE_SEC}  
      - VERSION=${TSTORE_INTERFACE_TAG}    
      - LOG_LEVEL=${LOG_LEVEL}
    container_name: ${TSTORE_INTERFACE_NAME}
    hostname: ${TSTORE_INTERFACE_NAME}
    ports:
      - "${TSTORE_INTERFACE_PORT}:80"
    restart: unless-stopped

  tstore_ui:
    labels:
      - "Version=${TSTORE_UI_TAG}"
      - "ID=${TSTORE_ID}"
    image: "transpara/tstore-ui:${TSTORE_UI_TAG}"
    environment:
      - TSTORE_INTERFACE_URL=http://${TSTORE_INTERFACE_NAME}:80/api/v1
      - VERSION=${TSTORE_UI_TAG}    
      - LOG_LEVEL=${LOG_LEVEL}
    container_name: ${TSTORE_UI_NAME}
    hostname: ${TSTORE_UI_NAME}
    ports:
      - "${TSTORE_UI_PORT}:8080"
    restart: unless-stopped

networks:
   default:
      name: transpara
      external: true

