apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: transpara-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Engine used for sending and reading data to/from tStore
  displayName: TStoreInterface
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - interface
  - tstore
  links:
  - name: Transpara Operator
    url: https://transpara-operator.domain
  maintainers:
  - email: diego.castro@transpara.com
    name: Diego
  maturity: alpha
  provider:
    name: transpara
  version: 0.0.0
