version: "3.9"
   
services:
  tsystem:
    labels:
      - "Version=${TSYSTEM_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tsystem:${TSYSTEM_TAG}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsystem_api_data:/app/database
    container_name: ${TSYSTEM_NAME}_api
    hostname: ${TSYSTEM_NAME}_api
    environment:
      - EXTERNAL_PORT=${TSYSTEM_PORT}
      - TSYSTEM_TAG=${TSYSTEM_TAG}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - CONTAINER_HOST=${CONTAINER_HOST}
      - USERNAME=${USERNAME}
      - SSH_PORT=${SSH_PORT}
      - DOCKER_FILE_BASE_PATH=${DOCKER_FILE_BASE_PATH}
      - DOCKER_FILE_TEMPLATE_PATH=${DOCKER_FILE_TEMPLATE_PATH}
    ports:
      - "0.0.0.0:${TSYSTEM_PORT}:80"
    restart: unless-stopped

  tcache:
    labels:
      - "Version=${TSYSTEM_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tcache:${TSYSTEM_TAG}"
    volumes:
      - tsystem_cache_data:/data  
    container_name: ${TSYSTEM_NAME}_cache
    hostname: ${TSYSTEM_NAME}_cache
    ports:
      - "0.0.0.0:${REDIS_PORT}:6379"
    restart: unless-stopped      
  
  tsystem_ui:
    labels:
      - "Version=${TSYSTEM_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tsystem-ui:${TSYSTEM_TAG}"
    container_name: ${TSYSTEM_NAME}_ui
    hostname: ${TSYSTEM_NAME}_ui
    environment:
      - NEXT_PUBLIC_TSYSTEM_API_URL=http://${CONTAINER_HOST}:${TSYSTEM_PORT}${TSYSTEM_API_ENDPOINT}
      - NEXT_PUBLIC_CONTAINER_HOST=${CONTAINER_HOST}
    ports:
      - "0.0.0.0:${TSYSTEM_UI_PORT}:3000"
    restart: unless-stopped

networks:
   default:
      name: transpara
      external: true

volumes:
  tsystem_api_data:
      name: tsystem_api_data_${TSYSTEM_ID}
  tsystem_cache_data:
      name: tsystem_cache_data_${TSYSTEM_ID}


# docker run -v $PWD/p3x-redis-ui-settings:/settings -h docker-p3x-redis-ui -p 7843:7843 -t -i patrikx3/p3x-redis-ui
