version: "3.9"
   
services:
  tsystem:
    labels:
      - "Version=${TSYSTEM_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tsystem:${TSYSTEM_TAG}"
    volumes:
      - tsystem_api_data:/app/database
    container_name: ${TSYSTEM_NAME}_api
    hostname: ${TSYSTEM_NAME}_api
    environment:
      - TSYSTEM_TAG=${TSYSTEM_TAG}
      - CONTAINER_HOST=${CONTAINER_HOST}
      - USERNAME=${USERNAME}
      - SSH_PORT=${SSH_PORT}
    ports:
      - "0.0.0.0:${TSYSTEM_PORT}:80"
    restart: unless-stopped

  tcache:
    labels:
      - "Version=${TSYSTEM_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tcache:${TSYSTEM_TAG}"
    volumes:
      - tsystem_cache_data:/data  
    container_name: ${TSYSTEM_NAME}_cache
    hostname: ${TSYSTEM_NAME}_cache
    ports:
      - "0.0.0.0:${REDIS_PORT}:6379"
    restart: unless-stopped      

networks:
   default:
      name: transpara

volumes:
  tsystem_api_data:
      name: tsystem_api_data_${TSYSTEM_ID}
  tsystem_cache_data:
      name: tsystem_cache_data_${TSYSTEM_ID}


# docker run -v $PWD/p3x-redis-ui-settings:/settings -h docker-p3x-redis-ui -p 7843:7843 -t -i patrikx3/p3x-redis-ui
