version: "3.9"
   
services:
  tsystem:
    labels:
      - "Version=${TSYSTEM_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tsystem:${TSYSTEM_TAG}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsystem_data:/app/database
      - /home/transpara:/home/transpara
    container_name: ${TSYSTEM_NAME}_api
    hostname: ${TSYSTEM_NAME}_api
    environment:
      - TSYSTEM_TAG=${TSYSTEM_TAG}
      - CONTAINER_HOST=${CONTAINER_HOST}
      - USERNAME=${USERNAME}
      - SSH_PORT=${SSH_PORT}
    ports:
      - "0.0.0.0:${TSYSTEM_PORT}:80"
    restart: unless-stopped
    logging: 
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        syslog-format: "rfc3164"
        tag: "node-${TSYSTEM_NAME}_api"

  tredis:
    labels:
      - "Version=${TCACHE_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tcache:${TCACHE_TAG}"
    volumes:
      - tredis_data:/data  
    container_name: ${TSYSTEM_NAME}_tcache
    hostname: ${TSYSTEM_NAME}_tcache
    ports:
      - "0.0.0.0:${REDIS_PORT}:6379"
    restart: unless-stopped      
    logging: 
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        syslog-format: "rfc3164"
        tag: "node-${TSYSTEM_NAME}_redis"      
  
  tsystem_ui:
    labels:
      - "Version=${TSYSTEM_UI_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tsystem-ui:${TSYSTEM_UI_TAG}"
    container_name: ${TSYSTEM_NAME}_ui
    hostname: ${TSYSTEM_NAME}_ui
    environment:
      - NEXT_PUBLIC_TSYSTEM_API_URL=http://${CONTAINER_HOST}:${TSYSTEM_PORT}${TSYSTEM_API_ENDPOINT}
      - NEXT_PUBLIC_CONTAINER_HOST=${CONTAINER_HOST}
    ports:
      - "0.0.0.0:${TSYSTEM_UI_PORT}:3000"
    restart: unless-stopped
    logging: 
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        syslog-format: "rfc3164"
        tag: "node-${TSYSTEM_NAME}_api"

networks:
   default:
      name: transpara

volumes:
  tsystem_data:
      name: tsystem_api_data_${TSYSTEM_ID}
  syslog_data:
      name: tsystem_syslog_data_${TSYSTEM_ID}
  tredis_data:
      name: tsystem_redis_data_${TSYSTEM_ID}


# docker run -v $PWD/p3x-redis-ui-settings:/settings -h docker-p3x-redis-ui -p 7843:7843 -t -i patrikx3/p3x-redis-ui
