version: "3.9"

services:
  tsystem:
    labels:
      - "Version=${TSYSTEM_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tsystem:${TSYSTEM_TAG}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsystem_api_data:/app/database
    container_name: ${TSYSTEM_NAME}_api
    hostname: ${TSYSTEM_NAME}_api
    environment:
      - EXTERNAL_PORT=${TSYSTEM_PORT}
      - TSYSTEM_TAG=${TSYSTEM_TAG}
      - TCACHE_HOST=${TCACHE_HOST}
      - TCACHE_PORT=${TCACHE_PORT}
      - CONTAINER_HOST=${CONTAINER_HOST}
      - USERNAME=${USERNAME}
      - SSH_PORT=${SSH_PORT}
      - DOCKER_FILE_BASE_PATH=${DOCKER_FILE_BASE_PATH}
      - DOCKER_FILE_TEMPLATE_PATH=${DOCKER_FILE_TEMPLATE_PATH}
    ports:
      - "0.0.0.0:${TSYSTEM_PORT}:80"
    restart: unless-stopped

  tcache:
    labels:
      - "Version=${TSYSTEM_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tcache:${TSYSTEM_TAG}"
    volumes:
      - tsystem_cache_data:/data  
    container_name: ${TSYSTEM_NAME}_cache
    hostname: ${TSYSTEM_NAME}_cache
    ports:
      - "0.0.0.0:${TCACHE_PORT}:6379"
    restart: unless-stopped
      
  tsystem_ui:
    labels:
      - "Version=${TSYSTEM_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tsystem-ui:${TSYSTEM_TAG}"
    container_name: ${TSYSTEM_NAME}_ui
    hostname: ${TSYSTEM_NAME}_ui
    environment:
      - NEXT_PUBLIC_TSYSTEM_API_URL=http://${CONTAINER_HOST}:${TSYSTEM_PORT}${TSYSTEM_API_ENDPOINT}
      - NEXT_PUBLIC_CONTAINER_HOST=${CONTAINER_HOST}
    ports:
      - "0.0.0.0:${TSYSTEM_UI_PORT}:3000"
    restart: unless-stopped

  tsystem_broker:
    labels:
      - "Version=${TEVENT_BROKER_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tevent-broker:${TEVENT_BROKER_TAG}"
    container_name: ${TSYSTEM_NAME}_broker
    hostname: ${TSYSTEM_NAME}_broker
    ports:
      - "0.0.0.0:${BROKER_MQTT_PORT}:1883"
      - "0.0.0.0:${BROKER_WEBSERVICE_PORT}:9001"
    restart: unless-stopped
    profiles:
      - event

  tsystem_event:
    labels:
      - "Version=${TEVENT_PROCESSOR_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "transpara/tevent-processor:${TEVENT_PROCESSOR_TAG}"
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - VERSION=${TEVENT_PROCESSOR_TAG}
      - TEVENTBROKER_HOST=${TSYSTEM_NAME}_broker
      - TEVENTBROKER_PORT=1883
      - TSYSTEM_API_URL=http://${TSYSTEM_NAME}_api:80${TSYSTEM_API_ENDPOINT}
      - WORKER_COUNT=${EVENT_WORKER_COUNT}
      - SUBSCRIPTION_REFRESH_INTERVAL_SEC=${EVENT_SUBSCRIPTION_REFRESH_INTERVAL_SEC}  
    container_name: ${TSYSTEM_NAME}_event
    hostname: ${TSYSTEM_NAME}_event
    restart: unless-stopped
    profiles:
      - event

  tsystem_event_mgmt:
    labels:
      - "Version=${TEVENT_MANAGEMENT_TAG}"
      - "ID=${TSYSTEM_ID}"
    image: "cedalo/management-center:${TEVENT_MANAGEMENT_TAG}"
    environment:
      - CEDALO_MC_BROKER_ID=mosquitto
      - CEDALO_MC_BROKER_NAME=Mosquitto
      - CEDALO_MC_BROKER_URL=mqtt://${TSYSTEM_NAME}_broker:1883
      - CEDALO_MC_USERNAME=admin
      - CEDALO_MC_PASSWORD=BorgGoesLive!22
    ports:
      - "0.0.0.0:${EVENT_MGMT_PORT}:8088"          
    container_name: ${TSYSTEM_NAME}_event_mgmt
    hostname: ${TSYSTEM_NAME}_event_mgmt
    restart: unless-stopped
    profiles:
      - event

networks:
   default:
      name: transpara
      external: true

volumes:
  tsystem_api_data:
      name: tsystem_api_data_${TSYSTEM_ID}
  tsystem_cache_data:
      name: tsystem_cache_data_${TSYSTEM_ID}
