apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsystem-cache-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi