apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tsystem-api
spec:
  serviceName: tsystem-api
  selector:
    matchLabels:
      app: tsystem-api
  replicas: 2 
  template:
    metadata:
      labels:
        app: tsystem-api
    spec:
      containers:
      - name: tsystem-api
        image: harbor.nonprod.caas.energy.sug.pri/transpara-dev/tsystem:kube-test-operator
        imagePullPolicy: Always
        env:
        - name: EXTERNAL_PORT
          valueFrom:
            configMapKeyRef:
              name: tsystem-config
              key: TSYSTEM_PORT
        - name: TSYSTEM_TAG
          valueFrom:
            configMapKeyRef:
              name: tsystem-config
              key: TSYSTEM_TAG
        - name: TCACHE_HOST
          valueFrom:
            configMapKeyRef:
              name: tsystem-config
              key: TCACHE_HOST
        - name: TCACHE_PORT
          valueFrom:
            configMapKeyRef:
              name: tsystem-config
              key: TCACHE_PORT
        - name: CONTAINER_HOST
          valueFrom:
            configMapKeyRef:
              name: tsystem-config
              key: CONTAINER_HOST
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: tsystem-config
              key: USERNAME
        - name: SSH_PORT
          valueFrom:
            configMapKeyRef:
              name: tsystem-config
              key: SSH_PORT
        ports:
        - containerPort: 80
        volumeMounts:
        - name: tsystem-api-data
          mountPath: /app/database
      imagePullSecrets:
        - name: transpara-docker-secret
      volumes:
      - name: tsystem-api-data
        persistentVolumeClaim:
          claimName: tsystem-api-data-claim
---

apiVersion: v1
kind: Service
metadata:
  name: tsystem-api
spec:
  selector:
    app: tsystem-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort

