version: "3.9"
   
services:
  extractor_telegraf:
    image: "transpara/extractor_telegraf:${EXTRACTOR_TAG}"
    volumes:
      - ${PWD}/data:/app/data
    environment:
      - tstore_api_url=${TSTORE_API_URL} 
      - folder_uid=${FOLDER_UID}
    container_name: ${NAME}
    ports:
      - "0.0.0.0:${EXTRACTOR_PORT}:80" 
    hostname: ${NAME}
    restart: unless-stopped
    logging: 
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        syslog-format: "rfc3164"
        tag: extractor_${NAME}

networks:
   default:
      name: transpara

