apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ID: ""
    Version: ""
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: tmon-db
  name: tmon-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tmon-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        ID: ""
        Version: ""
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/transpara: "true"
        io.kompose.service: tmon-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: 'transpara/tmon-database:'
          name: tmon-db
          ports:
            - containerPort: 5432
              hostIP: 0.0.0.0
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: tmon-data
      restartPolicy: Always
      volumes:
        - name: tmon-data
          persistentVolumeClaim:
            claimName: tmon-data
status: {}
