global:
  imagePullSecret: transpara-docker-secret
  imagePullPolicy: Always
  
tStoreInterface:
  name: tstore-interface
  replicas: 2
  image:
    repository: transpara/tstore-interface
    tag: "kube-test"
  config:
    TSYSTEM_URL: http://tsystem-api-service:80/api/v1
    TSTORE_DB_URL: postgresql://postgres:a0ba-396f-4c57-9b4@my-db-primary:5432/postgres
    EXPOSE_METRICS: "true"
    TSTORE_ID: 16561dd1-1247-409b-be2d-50cd8f9bb20d
    TCACHE_HOST: tsystem-cache
    TCACHE_PORT: "6379"
    TCACHE_DB: "7"
    TCACHE_CONSIDER_STALE_SEC: "300"
    LOG_LEVEL: INFO
    BASE_PATH: "/tstore-interface"
  ports:
    - containerPort: 80
  service:
    type: NodePort
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30083
