global:
  imagePullSecret: transpara-docker-secret
  imagePullPolicy: Always
  
tStoreInterface:
  name: tstore-interface
  replicas: 1
  image:
    repository: transpara/tstore-interface
    tag: 0.178.0
  config:
    # Example: http://tsystem-api:80/api/v1
    TSYSTEM_URL: http://tsystem-api:80/api/v1
    # Example: postgresql://postgres:a0ba-396f-4c57-9b4@my-db-primary:5432/postgres
    TSTORE_DB_WRITE_URL: <<TSTORE_DB_WRITE_URL>>
    TSTORE_DB_READ_URL: <<TSTORE_DB_READ_URL>>
    EXPOSE_METRICS: "true"
    TSTORE_ID: test-id
    TCACHE_HOST: tsystem-cache
    TCACHE_PORT: "6379"
    TCACHE_DB: "7"
    TCACHE_CONSIDER_STALE_SEC: "300"
    LOG_LEVEL: INFO
    BASE_PATH: "/tstore/api/v1"
    HISTORICAL_RETRY_DAYS_TIERS: "[1,7,30]"
  ports:
    - containerPort: 80
  service:
    type: NodePort
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30083

tStoreUi:
  name: tstore-ui
  replicas: 1
  image:
    repository: transpara/tstore-ui
    tag: kube-test
  config:
    BASE_PATH: "/tstore/ui"
    LOG_LEVEL: INFO 
  ports:
    - containerPort: 8080
  service:
    type: NodePort
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        nodePort: 30084 

# used for init container wait-tstore
tStore:
  host: tstore.tstore
  port: 5432
