apiVersion: charts.transpara.com/v1
kind: CollectorTelegraf
metadata:
  name: <<NAME>>
spec:
  replicaCount: 1
  image:
    repo: "transpara/collector-telegraf"
    tag: "0.179.0"
    pullPolicy: IfNotPresent
  podAnnotations: {}
  podLabels: 
    app: <<NAME>>
  imagePullSecrets: 
    - name: transpara-docker-secret
  args: []
  env:
    - name: HOSTNAME
      value: "telegraf-polling-service"
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []
  updateStrategy: {}
  service:
    enabled: true
    type: ClusterIP
    annotations: {}
  rbac:
    create: true
    clusterWide: true
    rules:
      - apiGroups:
          - ""
        resources:
          - nodes
          - nodes/proxy
          - nodes/metrics
          - services
          - endpoints
          - pods
          - ingresses
          - configmaps
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - "extensions"
        resources:
          - ingresses/status
          - ingresses
        verbs:
          - get
          - list
          - watch
      - nonResourceURLs:
          - "/metrics"
        verbs:
          - get
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  config: <<TELEGRAF_CONFIG>>
  metrics:
    health:
      enabled: false
      service_address: "http://:8888"
      threshold: 5000.0
    internal:
      enabled: true
      collect_memstats: false
  pdb:
    create: false
    minAvailable: 1

