global: 
  imagePullSecret: transpara-docker-secret
  CONTAINER_HOST: "192.168.83.33"

tSystemPv:
  storageClassName: local-path
  capacity: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: "/transpara/data"

tSystemPvc:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  storage: 1Gi

tSystemApi:
  name: tsystem-api
  serviceName: tsystem-api-service
  replicas: 2
  image:
    repository: transpara/tsystem
    pullPolicy: IfNotPresent
  ports:
    containerPort: 80
    servicePort: 80
    nodePort: 30080
  volumeMount:
    name: tsystem-api-data
    mountPath: /app/database
  config:
    TSYSTEM_ID: "049f6ed7-e015-47cd-961c-8ae249cd412d"
    TSYSTEM_NAME: "tsystem"
    REDIS_PORT: "6379"
    REDIS_HOST: "tsystem-cache"
    TSYSTEM_PORT: "8000"
    USERNAME: "transpara"
    SSH_PORT: "22"
    TSYSTEM_UI_PORT: "3010"
    TSYSTEM_API_ENDPOINT: "/api/v1/"

tSystemCache:
  name: tsystem-cache
  serviceName: tsystem-cache-service
  replicas: 2
  image: 
    repository: transpara/tcache
    pullPolicy: IfNotPresent
  ports:
    containerPort: 6379
    servicePort: 6379
    nodePort: 30082

tSystemUi:
  name: tsystem-ui
  serviceName: tsystem-ui-service
  replicas: 2
  image:
    repository: transpara/tsystem-ui
    pullPolicy: IfNotPresent
  ports:
    containerPort: 3000
    servicePort: 3000
    nodePort: 30081

