global: 
  imagePullSecret: transpara-docker-secret
  imagePullPolicy: Always
  CONTAINER_HOST: localhost

# tsystem-api volume
tSystemApiPv:
  name: tsystem-api-data
  storageClassName: local-path
  capacity: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: "/transpara/data/volumes/tsystem-api-data"

tSystemApiPvc:
  name: tsystem-api-data-claim
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  storage: 1Gi

# tsystem-cache volume
tSystemCachePv:
  name: tsystem-cache-data
  storageClassName: local-path
  capacity: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: "/transpara/data/volumes/tsystem-cache-data"

tSystemCachePvc:
  name: tsystem-cache-data-claim
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  storage: 1Gi


tSystemApi:
  name: tsystem-api
  serviceName: tsystem-api-service
  replicas: 2
  image:
    repository: transpara/tsystem
  ports:
    containerPort: 80
    servicePort: 80
    nodePort: 30080
  volumeMount:
    name: tsystem-api-data
    mountPath: /app/database
  config:
    TSYSTEM_ID: "049f6ed7-e015-47cd-961c-8ae249cd412d"
    #TSYSTEM_NAME: "tsystem"
    #REDIS_PORT: "6379"
    #REDIS_HOST: "tsystem-cache"
    #TSYSTEM_PORT: "8000"
    USERNAME: "transpara"
    SSH_PORT: "22"
    #TSYSTEM_UI_PORT: "3010"
    TSYSTEM_API_ENDPOINT: "/api/v1/"

tSystemCache:
  name: tsystem-cache
  serviceName: tsystem-cache-service
  replicas: 2
  image: 
    repository: transpara/tcache
  ports:
    containerPort: 6379
    servicePort: 6379
  volumeMount:
    name: tsystem-cache-data
    mountPath: /data

tSystemUi:
  name: tsystem-ui
  serviceName: tsystem-ui-service
  replicas: 2
  image:
    repository: transpara/tsystem-ui
  ports:
    containerPort: 3000
    servicePort: 3000
    nodePort: 30081