global: 
  imagePullSecret: transpara-docker-secret
  imagePullPolicy: Always
  CONTAINER_HOST: localhost
  BASE_TSYSTEM_PATH: /tsystem

tSystemApiPv:
  name: tsystem-api-data
  storageClassName: local-path
  capacity: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: "/transpara/data/volumes/tsystem-api-data"

tSystemApiPvc:
  name: tsystem-api-data-claim
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  storage: 1Gi

tSystemCachePv:
  name: tsystem-cache-data
  storageClassName: local-path
  capacity: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: "/transpara/data/volumes/tsystem-cache-data"

tSystemCachePvc:
  name: tsystem-cache-data-claim
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  storage: 1Gi

tSystemApi:
  name: tsystem-api
  serviceName: tsystem-api
  replicas: 1
  image:
    repository: transpara/tsystem
    tag: "kube-test-operator"
  ports:
    containerPort: 80
    servicePort: 80
    # Provide nodePort to enable it
  volumeMount:
    name: tsystem-api-data
    mountPath: /data/database
  config:
    BASE_PATH: "/tsystem/api/v1"
    TSYSTEM_ID: "049f6ed7-e015-47cd-961c-8ae249cd412d"
    USERNAME: "transpara"
    SSH_PORT: "22"
    DOCKER_FILE_BASE_PATH: "/transpara/deployment"
    DOCKER_FILE_TEMPLATE_PATH: "/transpara/deployment/template"

tSystemCache:
  name: tsystem-cache
  serviceName: tsystem-cache
  replicas: 1
  image: 
    repository: transpara/tcache
  ports:
    containerPort: 6379
    servicePort: 6379
    # Provide nodePort to enable it
  volumeMount:
    name: tsystem-cache-data
    mountPath: /data

tSystemUi:
  name: tsystem-ui
  serviceName: tsystem-ui
  replicas: 1
  image:
    repository: transpara/tsystem-ui
    tag: "kube-test"
  ports:
    containerPort: 3000
    servicePort: 3000
    # Provide nodePort to enable it
  config:
    BASE_PATH: "/tsystem/ui"

# tSystemEventMgmt:
#   name: tsystem-event-mgmt
#   serviceName: tsystem-event-mgmt
#   replicas: 1
#   image:
#     repository: cedalo/management-center
#     tag: 2
#   ports:
#     containerPort: 8088
#     servicePort: 8088
#     nodePort: 30082
#   config:
#     username: admin
#     password: BorgGoesLive!22

# tSystemBroker:
#   name: tsystem-broker
#   serviceName: tsystem-broker
#   replicas: 1
#   image:
#     repository: transpara/tevent-broker
#     tag: 0.175.0
#   ports:
#     mqttPort: 1883
#     mqttContainerPort: 1883
#     webservicePort: 9001
#     webserviceContainerPort: 9001

# tSystemEvent:
#   name: tsystem-event
#   replicas: 1
#   image:
#     repository: transpara/tevent-processor
#     tag: "kube-test"
#   config:
#     logLevel: INFO
#     workerCount: 4
#     subscriptionRefreshInterval: 60

