apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tGraphApi.name | quote }}
spec:
  type: ClusterIP
  ports:
  - name: api
    port: {{ .Values.tGraphApi.ports.api }}
    targetPort: {{ .Values.tGraphApi.ports.api }}
  selector:
    app: {{ .Values.tGraphApi.name | quote }}

