apiVersion: v1
kind: PersistentVolume
metadata:
  name: tgraph-data-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/tgraph"

