apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.TGRAPH_NAME }}-tgraph-db
spec:
  type: ClusterIP
  ports:
  - name: lab
    port: {{ .Values.tGraphDb.ports.lab }}
    targetPort: {{ .Values.tGraphDb.ports.lab }}
  - name: db
    port: {{ .Values.tGraphDb.ports.db }}
    targetPort: {{ .Values.tGraphDb.ports.db }}
  selector:
    app: {{ .Values.TGRAPH_NAME }}-tgraph-db

