apiVersion: v1
kind: Service
metadata:
  annotations:
    ID: ""
    Version: ""
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: tmon-server
  name: tmon-server
spec:
  ports:
    - name: "10051"
      port: 10051
      targetPort: 10051
  selector:
    io.kompose.service: tmon-server
status:
  loadBalancer: {}
