apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: manager-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: transpara-operator
    app.kubernetes.io/part-of: transpara-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
