version: "3.9"
   
services:

  tstore:
    image: "transpara/tstore-database:${TSTORE_TAG}"
    shm_size: '2gb'
    volumes:
      - tstore_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
      - PGPORT=5432
    container_name: ${TSTORE_NAME}_db
    hostname: ${TSTORE_NAME}_db
    ports:
      - "${TSTORE_PORT}:5432"
    restart: unless-stopped
    logging: 
      driver: syslog
      options:
        syslog-address: "udp://${SYSLOG_HOST}:514"
        syslog-format: "rfc3164"
        tag: "node-${TSTORE_NAME}_db"
  
  promscale:
    image: "transpara/tscale:${PROMSCALE_TAG}
    depends_on: 
      - tstore
    ports:
      - "${PROMSCALE_API_PORT}:9201"
      - "${MONITORING_PROMSCALE_PORT}:9202"      
    container_name: ${TSTORE_NAME}_promscale
    hostname: ${TSTORE_NAME}_promscale
    restart: unless-stopped 
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics
      PROMSCALE_DB_URI: postgres://${TSTORE_UNAME}:${TSTORE_PASSWORD}@${TSTORE_NAME}_db:5432/${TSTORE_DBNAME}?sslmode=allow 
    logging: 
      driver: syslog
      options:
        syslog-address: "udp://${SYSLOG_HOST}:514"
        syslog-format: "rfc3164"
        tag: "node-${TSTORE_NAME}_promscale"     

  tstore-api:
    image: "transpara/tstore-api:${TSTORE_API_TAG}"
    depends_on: 
      - tstore
      - promscale
    environment:
      - PROMSCALE_DB_URI=postgresql://${TSTORE_UNAME}:${TSTORE_PASSWORD}@${TSTORE_NAME}_db:5432/${TSTORE_DBNAME}
      - PROMSCALE_API_URI=http://${TSTORE_NAME}_promscale:9201/write
      - PROMSCALE_OTLP_URI=http://${MONITORING_PROMSCALE_HOST}:9202
      - EXPOSE_METRICS=${TSTORE_API_EXPOSE_METRICS}
      - EXPORT_TRACES=${TSTORE_API_EXPORT_TRACES}
      - TSTORE_NAME=${TSTORE_ID}
      - REDIS_HOST=${TSYSTEM_NAME}_redis
      - REDIS_PORT=${TREDIS_PORT}  
      - REDIS_DB=${TREDIS_SNAPSHOT_DB}  
      - USE_REDIS_FOR_SNAPSHOTS=${USE_REDIS_FOR_SNAPSHOTS}
      - REDIS_CONSIDER_STALE_SEC=${REDIS_CONSIDER_STALE_SEC}      
    container_name: ${TSTORE_NAME}_api
    hostname: ${TSTORE_NAME}_api
    ports:
      - "${TSTORE_API_PORT}:80"
    restart: unless-stopped
    logging: 
      driver: syslog
      options:
        syslog-address: "udp://${SYSLOG_HOST}:514"
        syslog-format: "rfc3164"
        tag: "node-${TSTORE_NAME}_api"

networks:
   default:
      name: transpara
      external: true

volumes:
   tstore_data:
      name: tstore_db_data_${TSTORE_ID}
