version: "3.9"
   
services:

  tstore-database:
    labels:
      - "Version=${TSTORE_TAG}"
      - "ID=${TSTORE_ID}"
    image: "transpara/tstore-database:${TSTORE_TAG}"
#    shm_size: '2gb'
    volumes:
      - tstore_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
      - PGPORT=5432
      - TSTUNE_PROFILE=promscale # this is the profile for timescaledb-tune to optimize postgres for promscale-like loads (wal size, buffers, etc)
    container_name: ${TSTORE_NAME}_db
    hostname: ${TSTORE_NAME}_db
    ports:
      - "${TSTORE_PORT}:5432"
    restart: unless-stopped


  tstore-pool:
    image: "bitnami/pgbouncer:latest"
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRESQL_HOST=${TSTORE_NAME}_db
      - POSTGRESQL_DATABASE=postgres
      - PGBOUNCER_PORT=6432
      - PGBOUNCER_QUERY_WAIT_TIMEOUT=300
      - PGBOUNCER_MAX_DB_CONNECTIONS=100
    container_name: ${TSTORE_NAME}_pool
    hostname: ${TSTORE_NAME}_pool          


networks:
   default:
      name: transpara
      external: true

volumes:
   tstore_data:
      name: tstore_db_data_${TSTORE_ID}
