apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ID: ""
    Version: ""
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: tstore-database
  name: tstore-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tstore-database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        ID: ""
        Version: ""
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/transpara: "true"
        io.kompose.service: tstore-database
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: PGPORT
              value: "5432"
            - name: POSTGRES_DB
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: 'transpara/tstore-database:'
          name: -db
          ports:
            - containerPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: tstore-data
      hostname: _db
      restartPolicy: Always
      volumes:
        - name: tstore-data
          persistentVolumeClaim:
            claimName: tstore-data
status: {}
