apiVersion: v1
kind: PersistentVolume
metadata:
  name: tsystem-api-data
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/transpara/data/volumes/tsystem-api-data"