apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ID: ""
    Version: ""
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: code-server
  name: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: code-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        ID: ""
        Version: ""
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/transpara: "true"
        io.kompose.service: code-server
    spec:
      containers:
        - env:
            - name: DEFAULT_WORKSPACE
              value: /extensions
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/London
          image: 'transpara/tcode:'
          name: -vscode
          ports:
            - containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /extensions
              name: tcalc-modules
      restartPolicy: Always
      volumes:
        - name: tcalc-modules
          persistentVolumeClaim:
            claimName: tcalc-modules
status: {}
