apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: tcore-worker
  name: tcore-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tcore-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/transpara: "true"
        io.kompose.service: tcore-worker
    spec:
      containers:
        - args:
            - /app/run-celeryworker.sh
          env:
            - name: CELERY_BROKER_URL
              value: redis://:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://:6379/1
            - name: OTEL_EXPORTER_HOST
              value: tstore_tscale
            - name: REDIS_HOST
            - name: REDIS_PORT
              value: "6379"
            - name: TAUTH_HOST
            - name: TAUTH_PORT
              value: "8080"
            - name: TCORE_ID
            - name: TCORE_NAME
            - name: TGRAPH_HOST
              value: _tcore_db
            - name: TGRAPH_PORT
              value: "7687"
          image: transpara/tcore-api:develop
          name: -tcore-worker
          resources: {}
      hostname: _tcore_worker
      restartPolicy: Always
status: {}
